(require 'conf-projectile)
(require 'conf-cmake-project)
(require 'conf-python-project)
(require 'conf-js-project)
(require 'conf-gradle-project)
(require 'conf-idea)
(require 'conf-qt-project)
(require 'conf-linux-kernel)

(provide 'load-project-mode)
